// Predefined medical specialties for doctor signup
export const DOCTOR_SPECIALTIES = [
  'Cardiology',
  'Dermatology',
  'Orthopedics',
  'Neurology',
  'Oncology',
  'Pediatrics',
  'Obstetrics & Gynecology',
  'Ophthalmology',
  'ENT (Ear, Nose, Throat)',
  'Gastroenterology',
  'Urology',
  'Nephrology',
  'Endocrinology',
  'Hematology',
  'Rheumatology',
  'Pulmonology',
  'Psychiatry',
  'Radiology',
  'Anesthesiology',
  'Emergency Medicine',
  'Family Medicine',
  'Internal Medicine',
  'General Surgery',
  'Plastic Surgery',
  'Neurosurgery',
  'Cardiothoracic Surgery',
  'Orthopedic Surgery',
  'Dental Surgery',
  'Cosmetic Dentistry',
  'Orthodontics',
  'Hair Transplant',
  'Bariatric Surgery',
  'IVF & Fertility',
  'Organ Transplant',
  'Physical Therapy',
  'Alternative Medicine',
  'Other',
]
